import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import Hero from "./Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mayank Maroliya Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      {/* <Header /> */}
      <div className="min-h-full">
        {/* <Header /> */}
        <Hero />
      </div>
    </>
  );
}
